# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13KNDp4F1wjndC6P18YLeQo4lpwso2TUG
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

data = pd.read_csv("/content/sample.csv")
data.head()

plt.scatter(data.age, data.job)

x = data[["age"]]

y = data["job"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

model = LogisticRegression()

#model train
model.fit(x_train, y_train)

#model test
model.predict(x_test)

x_test

y_test

#model accuracy
model.score(x_test, y_test)

#apply the model for new data

age = [[28]]
model.predict(age)

